import {db,configured,value,show} from './common.js';
const $=id=>document.getElementById(id);let leads=[];let filtered=[];
function safeCsv(v){let s=String(v??'');if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}
function cell(tr,text){const td=document.createElement('td');td.textContent=text??'';tr.append(td);return td}
function render(){const q=value('search').toLowerCase();filtered=leads.filter(x=>(!value('filterCenter')||x.center===value('filterCenter'))&&(!value('filterStatus')||x.status===value('filterStatus'))&&(!q||[x.parent_name,x.mobile,x.email,x.child_name].some(v=>String(v||'').toLowerCase().includes(q))));$('count').textContent='('+filtered.length+')';$('rows').replaceChildren();for(const x of filtered){const tr=document.createElement('tr');cell(tr,new Date(x.created_at).toLocaleString());cell(tr,x.parent_name);cell(tr,x.mobile);cell(tr,x.email);cell(tr,x.child_name);cell(tr,x.child_age);cell(tr,x.center);cell(tr,x.program);cell(tr,x.source);const st=document.createElement('td');const select=document.createElement('select');for(const s of ['New','Contacted','Trial Scheduled','Converted','Not Interested']){const opt=new Option(s,s);select.add(opt)}select.value=x.status;st.append(select);tr.append(st);const ft=document.createElement('td');const date=document.createElement('input');date.type='date';date.value=x.follow_up_date||'';ft.append(date);tr.append(ft);cell(tr,x.notes);const action=document.createElement('td');const btn=document.createElement('button');btn.textContent='Save';btn.className='secondary';btn.onclick=async()=>{btn.disabled=true;const {error}=await db.from('gsa_leads').update({status:select.value,follow_up_date:date.value||null,updated_at:new Date().toISOString()}).eq('id',x.id);if(error)show('dashboardMsg',error.message,true);else{x.status=select.value;x.follow_up_date=date.value||null;show('dashboardMsg','Lead updated.')}btn.disabled=false};action.append(btn);tr.append(action);$('rows').append(tr)}}}
async function load(){show('dashboardMsg','Loading leads...');const {data,error}=await db.from('gsa_leads').select('*').order('created_at',{ascending:false}).limit(5000);if(error){show('dashboardMsg',error.message,true);return}leads=data||[];show('dashboardMsg',leads.length===5000?'Showing latest 5,000 leads. Export is limited to loaded records.':'Loaded '+leads.length+' leads.');render()}
async function authView(){if(!configured){show('loginMsg','Configure config.js first.',true);return}const {data}=await db.auth.getSession();const signed=!!data.session;$('loginCard').classList.toggle('hide',signed);$('dashboard').classList.toggle('hide',!signed);if(signed)await load()}
$('loginForm').onsubmit=async e=>{e.preventDefault();if(!configured)return;const {error}=await db.auth.signInWithPassword({email:value('email'),password:value('password')});if(error)show('loginMsg',error.message,true);else await authView()};$('logout').onclick=async()=>{await db.auth.signOut();await authView()};$('refresh').onclick=load;for(const id of ['filterCenter','filterStatus','search'])$(id).addEventListener('input',render);
$('export').onclick=()=>{const cols=['created_at','parent_name','mobile','email','child_name','child_age','center','program','source','status','follow_up_date','notes'];const csv='\uFEFF'+[cols.map(safeCsv).join(','),...filtered.map(x=>cols.map(c=>safeCsv(x[c])).join(','))].join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='growstrong-leads-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
authView();
